### ISSUE TITLE
BND representation

### ISSUE THREAD

**Issue by nnariai** [fritzsedlazeck/Sniffles#121]
Hi @fritzsedlazeck ,

I noticed that Sniffles now reports BND as default for translocation, instead of TRA in VCF. Thank you for the modification! I like the BND representation more, as is is clearly described in the VCF v4.2 the spec: https://samtools.github.io/hts-specs/VCFv4.2.pdf

I found that for some cases (STRANDS=++ and --), BND representation in Sniffles' VCF is not following the VCF v4.2.  Also, the VCF spec specifies that two BND entries should appear in VCF with MATEID for a simple translocation, instead of using one BND entry with "STRANDS=XX". It would be great if you could consider modifying the BND representation (multiple BND entries for one TRA, using MATEID, instead of STRAND=XX), so that it complies more with the VCF spec.

Just to clarify, I pasted some TRA predictions with Sniffles vs. Manta v1.5.0. Please note that I used publicly available PacBio data data for Sniffles and Illumina data for Manta (both of SKBR3), so the predicted SV positions may not match exactly (but I assume two predictions refer to the same SV). With these examples, I'm trying to convince you that the Manta BND representation (below) would comply more with the VCF spec.

•	Case: +/+
**Sniffles**
`
chr4    119878405       33216   N       N[chr8:43843855[        .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.9;ZMW=29;STD_quant_start=0.462910;STD_quant_stop=0.597614;Kurtosis_quant_start=5.012614;Kurtosis_quant_stop=8.825857;SVTYPE=BND;SUPTYPE=SR;SVLEN=0;STRANDS=++;RE=29       GT:DR:DV        ./.:.:29
`

**Manta**
`
chr4    119878405       MantaBND:68981:0:1:0:0:0:0      T       T]chr8:43843854]        .       PASS    SVTYPE=BND;MATEID=MantaBND:68981:0:1:0:0:0:1;SOMATIC;SOMATICSCORE=127;BND_DEPTH=52;MATE_BND_DEPTH=56    PR:SR   85,0:72,0       43,14:51,17
`
`
chr8    43843854        MantaBND:68981:0:1:0:0:0:1      A       A]chr4:119878405]       .       PASS    SVTYPE=BND;MATEID=MantaBND:68981:0:1:0:0:0:0;SOMATIC;SOMATICSCORE=127;BND_DEPTH=56;MATE_BND_DEPTH=52    PR:SR   85,0:72,0       43,14:51,17
`

•	Case: +/-
**Sniffles**
`
chr1    229218656       32965   N       N[chr5:138549260[       .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.9;ZMW=26;STD_quant_start=0.620174;STD_quant_stop=0.554700;Kurtosis_quant_start=4.621364;Kurtosis_quant_stop=3.680843;SVTYPE=BND;SUPTYPE=SR;SVLEN=0;STRANDS=+-;RE=26       GT:DR:DV        ./.:.:26
`

**Manta**
`
chr1    229218656       MantaBND:18921:0:1:0:0:0:1      G       GC[chr5:138549260[      .       PASS    SVTYPE=BND;MATEID=MantaBND:18921:0:1:0:0:0:0;SVINSLEN=1;SVINSSEQ=C;SOMATIC;SOMATICSCORE=133;BND_DEPTH=70;MATE_BND_DEPTH=60      PR:SR   81,0:88,0       41,18:77,18
`
`
chr5    138549260       MantaBND:18921:0:1:0:0:0:0      T       ]chr1:229218656]CT      .       PASS    SVTYPE=BND;MATEID=MantaBND:18921:0:1:0:0:0:1;SVINSLEN=1;SVINSSEQ=C;SOMATIC;SOMATICSCORE=133;BND_DEPTH=60;MATE_BND_DEPTH=70      PR:SR   81,0:88,0       41,18:77,18
`

•	Case: -/+
**Sniffles**
`
chr3    141644031       33135   N       ]chr8:88792669]N        .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.9;ZMW=37;STD_quant_start=0.000000;STD_quant_stop=0.235702;Kurtosis_quant_start=7.512962;Kurtosis_quant_stop=13.846639;SVTYPE=BND;SUPTYPE=SR;SVLEN=0;STRANDS=-+;RE=37      GT:DR:DV        ./.:.:37
`

**Manta**
`
chr3    141644031       MantaBND:53870:0:1:0:1:0:0      T       ]chr8:88792669]T        .       PASS    SVTYPE=BND;MATEID=MantaBND:53870:0:1:0:1:0:1;SOMATIC;SOMATICSCORE=71;BND_DEPTH=51;MATE_BND_DEPTH=45     PR:SR   99,0:63,0       167,23:338,23
`
`
chr8    88792669        MantaBND:53870:0:1:0:1:0:1      A       A[chr3:141644031[       .       PASS    SVTYPE=BND;MATEID=MantaBND:53870:0:1:0:1:0:0;SOMATIC;SOMATICSCORE=71;BND_DEPTH=45;MATE_BND_DEPTH=51     PR:SR   99,0:63,0       167,23:338,23
`

•	Case: -/-
**Sniffles**
`
chr4    87565959        33204   N       ]chr19:58533693]N       .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.9;ZMW=10;STD_quant_start=1.760682;STD_quant_stop=0.836660;Kurtosis_quant_start=-0.429761
;Kurtosis_quant_stop=0.877551;SVTYPE=BND;SUPTYPE=SR;SVLEN=0;STRANDS=--;RE=10      GT:DR:DV        ./.:.:10
`

**Manta**
`
chr4    87565959        MantaBND:66424:0:1:0:1:0:0      T       [chr19:58533694[T       .       PASS    SVTYPE=BND;MATEID=MantaBND:66424:0:1:0:1:0:1;CIPOS=0,1;HOMLEN=1;HOMSEQ=T;SOMATIC;SOMATICSCORE=72;BND_DEPTH=51;MATE_BND_DEPTH=58 PR:SR   86,0:85,0       32,7:50,8
`
`
chr19   58533693        MantaBND:66424:0:1:0:1:0:1      A       [chr4:87565960[A        .       PASS    SVTYPE=BND;MATEID=MantaBND:66424:0:1:0:1:0:0;CIPOS=0,1;HOMLEN=1;HOMSEQ=C;SOMATIC;SOMATICSCORE=72;BND_DEPTH=58;MATE_BND_DEPTH=51 PR:SR   86,0:85,0       32,7:50,8
`

Thank you for taking a look!

**Comment by fritzsedlazeck** [comment]
Thanks for letting me know. Indeed for the BND I just converted the TRA record. So what you are saying is that each of the reported BND in Sniffles should be reported as two entries?

Thanks
Fritz

**Comment by nnariai** [comment]
Yes. For the cases for STRANDS=+- and -+, it would be a easy fix. However, for STRANDS=++ and --, I believe the BND representations (e.g. bracket orientation and nucleotide placement) should be fixed as per "5.4 Specifying complex rearrangements with breakends" in the vcf spec (https://samtools.github.io/hts-specs/VCFv4.2.pdf).

**Comment by fritzsedlazeck** [comment]
Thanks I will take a look as soon as possible.
Fritz

**Comment by cmdcolin** [comment]
I'd add a +1 to this

Note that the current way that <TRA> is reported with the END field representing the location on the CHR2 will cause some havoc for tabix indexing because tabix uses the END= field in INFO to make it's binning index. Similar xref https://github.com/samtools/htslib/issues/428

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.

**Comment by vmukhina** [comment]
Hi @fritzsedlazeck , this problem is still actual in new sniffles versions. I tested 2.0.2 and 2.0.7 and both give me BND representation without mateid like
chr1	8595284	Sniffles2.BND.B7B6S0	N	]chr14:87478116]N	60	PASS	PRECISE;SVTYPE=BND;SUPPORT=6;COVERAGE=30,26,33,34,32;STRAND=+-;NM=0.060;AF=0.194;CHR2=chr14;STDEV_POS=1.732	GT:GQ:DR:DV	0/0:9:25:6
I also don't see any complementary entries in files and there are no MATEID flags at all.
Please let me know if there is another version with fix. Thanks!

**Comment by xsvato01** [comment]
Hi, I am reporting what I believe is the same issue. I manually looked up what should be mate pairs in vcf:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Jan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Jan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>



<body link="#0563C1" vlink="#954F72">



20 | 1102330 | Sniffles2.BND.122S13 | N | [2:129432299[N | 60 | PASS | PRECISE;SVTYPE=BND;SUPPORT=1;COVERAGE=0,0,1,1,1;STRAND=+;AF=1.000;CHR2=2;STDEV_POS=0
-- | -- | -- | -- | -- | -- | -- | --
2 | 129434443 | Sniffles2.BND.4F5S1 | N | N[20:1102329[ | 60 | PASS | PRECISE;SVTYPE=BND;SUPPORT=1;COVERAGE=2,1,1,1,1;STRAND=+;AF=1.000;CHR2=20;STDEV_POS=0



</body>

</html>

This BND got only one supporting read, upon clicking on the primary and supplementary mapping sites in IGV you get this:

![image](https://user-images.githubusercontent.com/44240739/195610708-fb1cb6c8-3030-48c0-b65d-334e41880d4b.png)

In both, IGV and the vcf, you get all strands "+", however, according to the ALT encoding it would mean rather this:

![image](https://user-images.githubusercontent.com/44240739/195614446-13acd116-a333-4bb3-a1a1-c54eff91fe13.png)


For the variants to be mate pairs, the ALT should be in the format ]xxx]N + N[xxx[.

Please correct me if I am wrong

**Comment by ptrebert** [comment]
I am just looking at a callset created with v2.5.2 and there are still no MATEID fields reported for BNDs, so I guess closing this issue was premature or it's a regression.
